EXIT_OPTION = "Exit"
MAIN_MENU_OPTION = "Back To Main Menu"

MAIN_OPTION_ONE = "Add New Habit"
MAIN_OPTION_TWO = "Manage Habits"
MAIN_OPTION_THREE = "Analytics"

MAIN_MENU = [MAIN_OPTION_ONE, MAIN_OPTION_TWO, MAIN_OPTION_THREE, EXIT_OPTION]

EDIT_OPTION = "Edit"
DELETE_OPTION = "Delete"
CHECK_OPTION = "Check-Off"

MANAGE_HABIT_MENU = [EDIT_OPTION, DELETE_OPTION, CHECK_OPTION, MAIN_MENU_OPTION]

ANALYTICS_ALL_HABITS = "All Currently Tracked Habits"
ANALYTICS_HABITS_BY_PERIOD = "Habits By Periodicity"
ANALYTICS_LONGEST_RUN_ALL = "Longest Run Streak All Habits"
ANALYTICS_LONGEST_RUN_ONE = "Longest Run Streak Of Habit"

ANALYTICS_MENU = [ANALYTICS_ALL_HABITS, ANALYTICS_HABITS_BY_PERIOD, ANALYTICS_LONGEST_RUN_ALL,
    ANALYTICS_LONGEST_RUN_ONE, MAIN_MENU_OPTION]

PERIODS = [
    "Daily", "Weekly", "Monthly", "Yearly"
]